### ISSUE TITLE
Is this the same code that's on the YubiKey 4?

### ISSUE THREAD

**Issue by jeremyd2019** [Yubico/ykneo-oath#13]
I'm attempting to figure out the protocol, using the docs in here, the code of the applet, and the code of [yubikey manager](https://github.com/Yubico/yubikey-manager).  I'm finding some missing things in the applet code, like the require touch property flag.  Given that this repo's name is 'ykneo', is there some other repo for the yubikey 4?  Or what am I missing?

**Comment by dainnilsson** [comment]
Sorry, we hadn't updated the protocol specification for YubiKey 4 specific functionality. I have now done so, and moved it to a new location: https://developers.yubico.com/OATH/YKOATH_Protocol.html
Functionality that is only available on YubiKey 4 should be clearly marked, let me know if you have any other questions.
